  Skin_ListSecond = "<table border='0' width='100%'>"
  Skin_ListSecond = Skin_ListSecond + "<tr height='24'>"
  Skin_ListSecond = Skin_ListSecond + "<td width='24' background='images/tile_sub.gif'>　</td>"
  Skin_ListSecond = Skin_ListSecond + "<td width='24' background='images/tile_sub.gif'>　</td>"
  Skin_ListSecond = Skin_ListSecond + "<td background='images/tile_sub.gif'>{BBSTitle}</td>"
  Skin_ListSecond = Skin_ListSecond + "<td width='80'  background='images/tile_sub.gif' align='center'>{BBSPostUser}</td>"
  Skin_ListSecond = Skin_ListSecond + "<td width='40'  background='images/tile_sub.gif' align='center'>{BBSReply}</td>"
  Skin_ListSecond = Skin_ListSecond + "<td width='40'  background='images/tile_sub.gif' align='center'>{BBSView}</td>"
  Skin_ListSecond = Skin_ListSecond + "<td width='200' background='images/tile_sub.gif'>{BBSLastPostTime}<br>最后发表：{BBSLastPostUser}</td>"
  Skin_ListSecond = Skin_ListSecond + "</tr></table>" 
